FROM python:3.7-alpine

WORKDIR bsdnumber/

RUN apk add --no-cache gcc musl-dev

COPY tests/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN pip install --no-cache-dir .

CMD ["ash", "tests/number_test.sh" ]
